version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
      - backend